buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id 'java'
    id 'jacoco'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'io.sentry.jvm.gradle' version '6.17.0'
    id 'org.sonarqube' version '7.3.1.8318'
}

group = 'hexlet.code'
version = '0.0.1-SNAPSHOT'
description = 'app'

def sentryAuthToken = System.getenv('SENTRY_AUTH_TOKEN')

sentry {
    includeSourceContext = sentryAuthToken != null
    autoUploadSourceContext = sentryAuthToken != null
    org = 'dualboot-2t'
    projectName = 'java-spring-boot'
    authToken = sentryAuthToken
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jacoco {
    toolVersion = '0.8.14'
}

sonar {
    properties {
        property 'sonar.projectKey', 'ponttor_java-project-99'
        property 'sonar.organization', 'ponttor'
        property 'sonar.host.url', 'https://sonarcloud.io'
        property 'sonar.coverage.jacoco.xmlReportPaths',
                layout.buildDirectory.file('reports/jacoco/test/jacocoTestReport.xml').get().asFile.path
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'
    implementation 'org.mapstruct:mapstruct:1.6.3'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'org.postgresql:postgresql'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('jacocoTestReport') {
    dependsOn tasks.named('test')
    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }
}

tasks.named('check') {
    dependsOn tasks.named('jacocoTestReport')
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}
